### ISSUE TITLE
Storm read

### ISSUE THREAD

**Issue by haq** [TornadoClientDev/Storm-Anticheat#29]
HEY I HAVE GLIDE BUG IN MY ANTICHEAT PLS HELP. I AM FUULL TIME ANTICHEAT DEV. PLS PLS PLS HELP

**Comment by Spazzinq** [comment]
lul

**Comment by haq** [comment]
THIS IS NOT FUNNY. I AM IN NEED OF SERIOUS HELP.

**Comment by x0** [comment]
HELLO IM HAVING THE SAME ISSUE SEND HELP

**Comment by aidanwd** [comment]
YES YES YES

**Comment by keksbg** [comment]
HELP ME IM DYIEING INSIDE

**Comment by ghost** [comment]
PLZ HELP ME I NEED HELP THIS IS VERY SERIOUS
