### ISSUE TITLE
Stay off AAC's bug tracker forms

### ISSUE THREAD

**Issue by Slimerblue22** [TornadoClientDev/Storm-Anticheat#32]
IM A LOSER AND IM A AAC DEV BECAUSE I CANT GET A JOB OMGGG PLZ HELP ME TORNADO
*^^^ here we see a really good forum owner lol*

**Comment by TornadoClientDev** [comment]
hello salty

**Comment by Slimerblue22** [comment]
Oh hey, how you doing, like the edit lol. Didn't know I was an AAC dev, wow!

**Comment by TornadoClientDev** [comment]
yo you there

**Comment by Slimerblue22** [comment]
Sure, whats up. I get emails when someone reply's to this :P
