### ISSUE TITLE
Fly, Speed, Glide falses

### ISSUE THREAD

**Issue by brandonlooksdumb** [TornadoClientDev/Storm-Anticheat#70]
Hello 👋 i found some falses with Storm.

Fly (B), Glide (A) and Speed (OnGround) make false positives when we're stuck in a block.
When you jump off the edge of a carpet, you make Speed (OnGround) and Fly (A) alerts.
When you run and then stop all of a sudden and run again, you make Speed (OnGround) alerts.

That's it, except for that very good anti-cheat! Have a great day! 😜

**Comment by ghost** [comment]
OK thanks
